-- 대장균 개체 ID 와 자식 수 출력
-- 자식이 없다면 0
-- ID 오름차순
SELECT T.ID, IF (PARENT_ID IS NULL, 0, CNT) AS CHILD_COUNT
FROM (
        SELECT ED1.ID, ED2.PARENT_ID, COUNT(*) AS CNT
        FROM ECOLI_DATA ED1
        LEFT JOIN ECOLI_DATA ED2 ON ED1.ID = ED2.PARENT_ID
        GROUP BY ED1.ID, ED2.PARENT_ID
     ) AS T
