SELECT USER_ID, PRODUCT_ID
FROM (SELECT USER_ID, PRODUCT_ID, COUNT(*) AS CNT
        FROM ONLINE_SALE
        GROUP BY USER_ID, PRODUCT_ID
      ) AS T
WHERE CNT >= 2
ORDER BY USER_ID ASC, PRODUCT_ID DESC