-- (동일한 날짜, 회원 ID, 상품 ID) 1 DATA, 즉 각각 별개
-- ONLIN-OFFLINE 202203 판매 날짜, ID, 유저ID, 판매량 출력
-- OFFLINE USER_ID는 NULL로 출력
-- 판매일 기준 ASC, PRODUCT_ID ASC, USER_ID ASC
SELECT DATE_FORMAT(ON_OFFLINE_SALE.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE)
    UNION 
    (SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE)
    ) AS ON_OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC