-- 입양 간 동물, 보호기간이 가장 길었던 동물 두마리의 ID, NAME 조회, 보호기간이 긴 순으로 조회
SELECT AI.ANIMAL_ID, AI.NAME
FROM ANIMAL_INS AI 
INNER JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
ORDER BY (AO.DATETIME-AI.DATETIME ) DESC
LIMIT 2