-- 세단, SUV
-- 2022-11-1 ~ 2022-11-30 까지 대여 가능
-- 30일간 대여금액 50만 <= X < 200만
-- ID, TYPE, 금액 출력
-- 대여 금액 내림차순, TYPE 오름차순, ID 내림차순

WITH DP AS (
    SELECT CAR_TYPE, 
     DURATION_TYPE, 
    (1 - (DISCOUNT_RATE / 100)) AS DISCOUNT_RATE 
    
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE IN ('세단', 'SUV')
        AND DURATION_TYPE = '30일 이상'
) 


SELECT CCDP.CAR_ID, CCDP.CAR_TYPE, FEE
FROM (
    SELECT CCC.CAR_ID, CCC.CAR_TYPE, FLOOR(DP.DISCOUNT_RATE * 30 * CCC.DAILY_FEE) AS FEE
        FROM CAR_RENTAL_COMPANY_CAR CCC
        JOIN DP ON CCC.CAR_TYPE = DP.CAR_TYPE
    ) AS CCDP 
            
WHERE CCDP.CAR_ID NOT IN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
            )
AND  FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CCDP.CAR_TYPE ASC, CCDP.CAR_ID DESC


