-- 음식 종류별, 즐겨찾기 수 max 식당의 음식 종류, ID, 식당이름, 즐겨찾기 수
-- 종류를 기준으로 내림차순
SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) AS FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (SELECT FOOD_TYPE, MAX(FAVORITES)
                 FROM REST_INFO
                 GROUP BY FOOD_TYPE)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC