-- 년월성별 별로 상품 구매한 회원수 집계
-- 년 월 성별 기준 오름차, 성별 정보 없는 경우 제외
SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH, UI.GENDER, COUNT(DISTINCT UI.USER_ID) AS USERS
FROM USER_INFO UI
JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, UI.GENDER
ORDER BY YEAR ASC, MONTH ASC, UI.GENDER ASC