-- 이름, 잡은수, 잡은 수 기준 내림차순
SELECT COUNT(FI.ID) AS FISH_COUNT, FNI.FISH_NAME AS FISH_NAME
FROM FISH_INFO FI JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
GROUP BY FNI.FISH_NAME
ORDER BY FISH_COUNT DESC