
-- 트럭, 대여 기록별 대여 금액(FEE)구하여, 대여 기록 ID, 대여 금액 리스트 출력
-- 대여 금액 내림차순, id 내림차순
 WITH CCDP AS (
    SELECT DURATION_TYPE, CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    WHERE CAR_TYPE = '트럭'
)
 
SELECT RH.HISTORY_ID, 
        ROUND(CC.DAILY_FEE * (DATEDIFF(END_DATE,START_DATE) + 1) * 
        (1 - (
            CASE
                WHEN (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1) >= 90 THEN (SELECT DISCOUNT_RATE FROM CCDP WHERE DURATION_TYPE = '90일 이상')
                WHEN (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1) >= 30 THEN (SELECT DISCOUNT_RATE FROM CCDP WHERE DURATION_TYPE = '30일 이상')
                WHEN (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1) >= 7  THEN (SELECT DISCOUNT_RATE FROM CCDP WHERE DURATION_TYPE = '7일 이상')
                ELSE 0
            END
        ) / 100)
    ) AS FEE
             
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
JOIN CAR_RENTAL_COMPANY_CAR CC ON RH.CAR_ID = CC.CAR_ID
WHERE CC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC