-- 2022-04-13 취소되지 않은 흉부외과(CS) 진료예약 내역
-- 진료 예약일시 기준 오름차순

SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT P ON A.PT_NO = P.PT_NO
JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
WHERE A.APNT_YMD LIKE '2022-04-13 %'
AND A.MCDP_CD = 'CS' 
AND A.APNT_CNCL_YMD IS NULL
ORDER BY A.APNT_YMD ASC

