-- 코드를 입력하세요
SET @HOUR = -1;

SELECT (@HOUR:= @HOUR + 1)  AS HOUR, 
(SELECT COUNT(*) 
 FROM ANIMAL_OUTS AO2 
 WHERE @HOUR = HOUR(AO2.DATETIME)
) AS COUNT
FROM ANIMAL_OUTS AO1
WHERE @HOUR < 23
ORDER BY HOUR

