SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
WHERE EXISTS (
    SELECT 1
    FROM SKILLCODES SC
    WHERE SC.CATEGORY = 'Front End' 
    AND (D.SKILL_CODE & SC.CODE) = SC.CODE
)
ORDER BY D.ID;