-- 완료, 총거래 금액 70만 이상, ID, 닉넴임, 총 거래액
SELECT UGU.USER_ID, UGU.NICKNAME, SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UGB 
    INNER JOIN USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
WHERE UGB.STATUS = 'DONE' 
GROUP BY UGU.USER_ID, UGU.NICKNAME
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES