-- 코드를 입력하hh
SELECT DATE_FORMAT(DATETIME,'%k') AS HOUR,
   COUNT(ANIMAL_ID) 
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR >= 9 AND HOUR <= 19
ORDER BY DATE_FORMAT(DATETIME,'%H')


// 깔끔한 정답
SELECT HOUR(DATETIME) AS HOUR,
        COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN '9' AND '19'
GROUP BY HOUR
ORDER BY HOUR
