-- 코드를 입력하hh
SELECT DATE_FORMAT(DATETIME,'%k') AS HOUR,
   COUNT(ANIMAL_ID) 
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME,'%H') >= 9 
AND DATE_FORMAT(DATETIME,'%H' ) <= 19
GROUP BY HOUR
ORDER BY DATE_FORMAT(DATETIME,'%H')


