-- 파이썬 C#스킬 가진 개발자, ID, EMAIL, FIRSTNAME, LASTNAME
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM  DEVELOPERS
WHERE EXISTS (
    SELECT 1
    FROM SKILLCODES S
    WHERE NAME IN ('C#', 'Python')
    AND SKILL_CODE & S.CODE != 0
)
ORDER BY ID