-- 코드를 입력하세요
SELECT DISTINCT CRCC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CRCC 
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CCRTH ON CRCC.CAR_ID = CCRTH.CAR_ID
WHERE MONTH(CCRTH.START_DATE) = 10
AND CRCC.CAR_TYPE = '세단'
ORDER BY CRCC.CAR_ID DESC;