-- 부서 ID, 영문 부서명, 평균 연봉
-- 평균 연봉은 소수점 첫째 자리 반올림, 컬럼명 AVG_SAL
-- 평균 연봉 기준 내림차순 정렬

SELECT HD.DEPT_ID, HD.DEPT_NAME_EN, ROUND(AVG(HE.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT HD
JOIN HR_EMPLOYEES HE ON HD.DEPT_ID = HE.DEPT_ID
GROUP BY HD.DEPT_ID, HD.DEPT_NAME_EN
ORDER BY AVG_SAL DESC;