-- 조회수가 가장 높은 중고거래 게시물에 대한 첨부파일 경로를 조회
-- BASE /home/grep/src/, BOARD_ID, FILENAME, EXT
-- FILE_ID DESC
SELECT CONCAT('/home/grep/src/', UGF.BOARD_ID, '/', UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE UGF
INNER JOIN USED_GOODS_BOARD UGB ON UGF.BOARD_ID = UGB.BOARD_ID
WHERE UGB.VIEWS = (SELECT MAX(VIEWS)
                FROM USED_GOODS_BOARD
              )
ORDER BY UGF.FILE_ID DESC

