SELECT COUNT(*) AS FISH_COUNT, MAX(FI.LENGTH) AS MAX_LENGTH, FI.FISH_TYPE
FROM (
    SELECT ID, IFNULL(LENGTH, 10) AS LENGTH, FISH_TYPE
    FROM FISH_INFO
) AS FI
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE