-- 평균 33CM 이상, 종류별 잡은 수, 최대 길이 , 종류
-- 종류 ASC, 10CM 이하 = 10CM

SELECT COUNT(ID) AS FISH_COUNT, MAX(IF (LENGTH IS NULL, 10, LENGTH)) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING MAX_LENGTH >= 33
ORDER BY FISH_TYPE ASC