SELECT 
    CASE
        WHEN SUM(IF(S.NAME = 'Python', 1, 0)) > 0 
         AND SUM(IF(S.CATEGORY = 'Front End', 1, 0)) > 0 THEN 'A'
        WHEN SUM(IF(S.NAME = 'C#', 1, 0)) > 0 THEN 'B'
        WHEN SUM(IF(S.CATEGORY = 'Front End', 1, 0)) > 0 THEN 'C'
    END AS GRADE,
    D.ID,
    D.EMAIL
FROM DEVELOPERS D
JOIN SKILLCODES S ON (D.SKILL_CODE & S.CODE) = S.CODE
GROUP BY D.ID, D.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE ASC, D.ID ASC;